/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Diego
 */
public class frmSplashScreen extends JFrame  {

    /**
     * Creates new form frmSplashScreen
     */
public frmSplashScreen() {

        initComponents();
        
        getContentPane().setBackground(new Color(221, 221, 221));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1150, 650); 
        int iconWidth = 32;
int iconHeight = 32;

ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/Vistas/resources/ignisFormsCircular.png"));
Image originalImage = iconoOriginal.getImage();

Image scaledImage = originalImage.getScaledInstance(iconWidth, iconHeight, Image.SCALE_SMOOTH);

setIconImage(scaledImage);

        setTitle("IGNIS");


        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                           doTask("Conectando a la base de datos ...", 10);
doTask("Estableciendo conexiones ...", 40);
doTask("Aplicando ajustes finales ...", 70);
doTask("Listo para comenzar ...", 100);
doTask("Proceso completado exitosamente ... ✅", 100);
                            dispose();
                            curvesPanel1.stop(); // Para detener la animación
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                }).start();
            }
        });
    }


public static void initFrmSplash() {
      FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("vistas.themes");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY,Font.PLAIN,13));
        FlatLightLaf.setup();
    frmSplashScreen vista = new frmSplashScreen();
    vista.setVisible(true);
  
}
    
    
    
    
    
     private void doTask(String taskName, int progress) throws Exception {
       lblEstado.setFont(new Font("Noto Color Emoji", Font.PLAIN, 14));
        lblEstado.setText(taskName);
        Thread.sleep(1000); //  For Test
        pro.setValue(progress);
    }
     
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curvesPanel1 = new Vistas.CurvesPanel();
        jLabel2 = new javax.swing.JLabel();
        pro = new Vistas.ProgressBarCustom();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        curvesPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/resources/ignisMini.png"))); // NOI18N
        curvesPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 250, 440));

        pro.setBackground(new java.awt.Color(255, 173, 122));
        pro.setBorder(null);
        pro.setForeground(new java.awt.Color(240, 139, 77));
        curvesPanel1.add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 240, 10));

        lblEstado.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(240, 139, 77));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curvesPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 270, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curvesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curvesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {             
                         
                frmSplashScreen splash = new frmSplashScreen();
                splash.setLocationRelativeTo(null); // Centrar el JFrame
                splash.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.CurvesPanel curvesPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEstado;
    private Vistas.ProgressBarCustom pro;
    // End of variables declaration//GEN-END:variables
}
