/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Aspirantes;
import Modelo.Recursos;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class itemAspirante extends javax.swing.JPanel {

    /**
     * Creates new form itemAspirante
     */
    public itemAspirante() {
        initComponents();
    }
    
     public Aspirantes getData() {
        return data;
    }
     
      public boolean isSelected() {
        return selected;
    }
      
    public void setSelected(boolean selected) {
    this.selected = selected;
    repaint();
    }
    
    private boolean selected;

    private Aspirantes data;
    
    public void setData(Aspirantes data) {
 this.data = data;

   int nuevoAncho = 150; 
int nuevoAlto = 150;  

try {
    // Obtener la ruta de la imagen desde el objeto data
    String rutaImagen = data.getFoto_aspirante(); // Asegúrate de que contenga la ruta completa

    // Cargar la imagen desde el sistema de archivos
    File file = new File(rutaImagen);
   
    // Verifica si el archivo existe
    if (!file.exists()) {
            imgAspirante.setIcon(new ImageIcon("/Vistas/resources/ignisFormsCircular.png")); // Cambia esto a tu imagen por defecto
            
        System.out.println("No se encontró el archivo en la ruta especificada: " + file.getAbsolutePath());
        // Opcional: puedes asignar una imagen por defecto o dejar el JLabel vacío
    }
    
    // Leer la imagen desde el archivo
    BufferedImage image = ImageIO.read(file);
    
    // Verifica si la imagen se ha leído correctamente
    if (image == null) {
        System.out.println("No se pudo leer la imagen desde la ruta especificada.");
    imgAspirante.setIcon(new ImageIcon("/Vistas/resources/ignisFormsCircular.png")); // Cambia esto a tu imagen por defecto
    }

    // Crear la imagen circular
    BufferedImage circularImage = imgRedondeada.makeCircularImage(image, nuevoAncho, nuevoAlto);
    
    // Asignar la imagen circular al JLabel
    imgAspirante.setIcon(new ImageIcon(circularImage));

} catch (IOException e) {
    // Opcional: puedes manejar la excepción asignando una imagen por defecto
    imgAspirante.setIcon(new ImageIcon("/Vistas/resources/ignisFormsCircular.png")); // Cambia esto a tu imagen por defecto
    
    
}


    // Asignar el nombre del Aspirante
    Nombre.setText("Nombre: " + data.getNombre_aspirante());

    // Asignar la Apellido
    
    Apellido.setText(data.getApellido_aspirante());
    
    // Asignar la Edad
   
    Edad.setText(Integer.toString(data.getEdad_usuario()));
    
    Dui.setText(data.getDui_aspirante());
    
    Progreso.setText(data.getProgreso_aspirante());
    
    Entrenamiento.setText(data.getEntrenamiento_aspirante());
    
    Mentor.setText(data.getBombero_Mentor());
    
    
}
    
@Override
protected void paintComponent(Graphics grphcs) {
    super.paintComponent(grphcs); // Llama al método para dibujar los componentes hijos

    Graphics2D g2 = (Graphics2D) grphcs.create();
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    // Dibuja el borde de color amarillo
    g2.setColor(Color.YELLOW); // Color del borde
    g2.drawRect(0, 0, getWidth() - 1, getHeight() - 1); // Dibujar el borde

    // Dibujar un borde adicional si está seleccionado
    if (selected) {
        g2.setColor(new Color(94, 156, 255)); // Color del borde cuando está seleccionado
        g2.drawRect(0, 0, getWidth() - 1, getHeight() - 1); // Borde más delgado si está seleccionado
    }

    g2.dispose(); // Libera los recursos gráficos
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgAspirante = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Dui = new javax.swing.JLabel();
        Entrenamiento = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Mentor = new javax.swing.JLabel();
        Progreso = new javax.swing.JLabel();

        Apellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Apellido.setText("Apellido");

        Nombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Nombre.setText("Nombre");

        Dui.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Dui.setText("Dui");

        Entrenamiento.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Entrenamiento.setText("Entrenamiento");

        Edad.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Edad.setText("Edad");

        Mentor.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Mentor.setText("Mentor");

        Progreso.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Progreso.setText("Progreso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(imgAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(Dui, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Entrenamiento)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(Mentor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(Edad)
                            .addComponent(Progreso)
                            .addComponent(Mentor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido)
                            .addComponent(Dui)
                            .addComponent(Entrenamiento))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Apellido;
    public javax.swing.JLabel Dui;
    public javax.swing.JLabel Edad;
    public javax.swing.JLabel Entrenamiento;
    public javax.swing.JLabel Mentor;
    public javax.swing.JLabel Nombre;
    public javax.swing.JLabel Progreso;
    public javax.swing.JLabel imgAspirante;
    // End of variables declaration//GEN-END:variables
}
