/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Aspirantes;
import Modelo.Recursos;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class itemAspirante extends javax.swing.JPanel {

    /**
     * Creates new form itemAspirante
     */
    public itemAspirante() {
        initComponents();
    }
    
     public Aspirantes getData() {
        return data;
    }
     
      public boolean isSelected() {
        return selected;
    }
      
    public void setSelected(boolean selected) {
    this.selected = selected;
    repaint();
    }
    
    private boolean selected;

    private Aspirantes data;
    
    public void setData(Aspirantes data) {
 this.data = data;

   int nuevoAncho = 150; 
int nuevoAlto = 150;  

try {
    // Obtener la ruta de la imagen desde el objeto data
    String rutaImagen = data.getFoto_aspirante(); // Asegúrate de que contenga la ruta completa

    // Cargar la imagen desde el sistema de archivos
    File file = new File(rutaImagen);
   
    // Verifica si el archivo existe
    if (!file.exists()) {
            imgAspirante.setIcon(new ImageIcon("/Vistas/resources/ignisFormsCircular.png")); // Cambia esto a tu imagen por defecto
            
        System.out.println("No se encontró el archivo en la ruta especificada: " + file.getAbsolutePath());
        // Opcional: puedes asignar una imagen por defecto o dejar el JLabel vacío
    }
    
    // Leer la imagen desde el archivo
    BufferedImage image = ImageIO.read(file);
    
    // Verifica si la imagen se ha leído correctamente
    if (image == null) {
        System.out.println("No se pudo leer la imagen desde la ruta especificada.");
    imgAspirante.setIcon(new ImageIcon("/Vistas/resources/ignisFormsCircular.png")); // Cambia esto a tu imagen por defecto
    }

    // Crear la imagen circular
    BufferedImage circularImage = imgRedondeada.makeCircularImage(image, nuevoAncho, nuevoAlto);
    
    // Asignar la imagen circular al JLabel
    imgAspirante.setIcon(new ImageIcon(circularImage));

} catch (IOException e) {
    // Opcional: puedes manejar la excepción asignando una imagen por defecto
    imgAspirante.setIcon(new ImageIcon("/Vistas/resources/ignisFormsCircular.png")); // Cambia esto a tu imagen por defecto
    
    
}


    // Asignar el nombre del Aspirante
    Nombre.setText( data.getNombre_aspirante());

    // Asignar la Apellido
    
    Apellido.setText(data.getApellido_aspirante());
    
    // Asignar la Edad
   
    Edad.setText(Integer.toString(data.getEdad_usuario()));
    
    Dui.setText(data.getDui_aspirante());
    
    Progreso.setText(data.getProgreso_aspirante());
    
    Entrenamiento.setText(data.getEntrenamiento_aspirante());
    
    Mentor.setText(data.getBombero_Mentor());
    
    
}
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgAspirante = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Dui = new javax.swing.JLabel();
        Entrenamiento = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Mentor = new javax.swing.JLabel();
        Progreso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 139, 77)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(imgAspirante, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, 162, 158));

        Apellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Apellido.setText("Apellido");
        add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 123, -1));

        Nombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Nombre.setText("Nombre");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 126, -1));

        Dui.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Dui.setText("Dui");
        add(Dui, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 140, -1));

        Entrenamiento.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Entrenamiento.setText("Entrenamiento");
        add(Entrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 400, 20));

        Edad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Edad.setText("Edad");
        add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 50, -1));

        Mentor.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Mentor.setText("Mentor");
        add(Mentor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 180, -1));

        Progreso.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Progreso.setText("Progreso");
        add(Progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 180, -1));

        jPanel1.setBackground(new java.awt.Color(240, 139, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(731, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel1.setText("Apellido");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Bombero mentor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 160, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setText("Edad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setText("Dui");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 50, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel6.setText("Progreso");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 80, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel7.setText("Entrenamiento");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 130, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Apellido;
    public javax.swing.JLabel Dui;
    public javax.swing.JLabel Edad;
    public javax.swing.JLabel Entrenamiento;
    public javax.swing.JLabel Mentor;
    public javax.swing.JLabel Nombre;
    public javax.swing.JLabel Progreso;
    public javax.swing.JLabel imgAspirante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
