/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Recursos;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego
 */
public class itemRecurso extends javax.swing.JPanel {

    /**
     * Creates new form itemRecurso
     */
    public itemRecurso() {
        initComponents();
         setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }
    
     public Recursos getData() {
        return data;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    private boolean selected;

    private Recursos data;

public void setData(Recursos data) {
    this.data = data;

    // Redimensionar la imagen
    int nuevoAncho = 100; // Cambia estos valores según tus necesidades
    int nuevoAlto = 100;  // Cambia estos valores según tus necesidades
    ImageIcon imagenRedimensionada = redimensionarImagen(data.getFotoRecurso(), nuevoAncho, nuevoAlto);
    
    imgRecurso.setIcon(imagenRedimensionada); // Corrige aquí

    // Asignar el nombre del recurso
    lblNombre.setText(data.getNombreRecurso());

    // Asignar la descripción del recurso
   String descripcion = "<html><div style='width: " + lblDescripcion.getWidth() + "px;'>" +
                         data.getDescripcionRecurso() + "</div></html>";
    lblDescripcion.setText(descripcion);
    // Asignar el estado del recurso
    lblEstado.setText("Estado: " + data.getEstadoRecurso());

    // Formatear y asignar la fecha de recepción del recurso
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    lblFecha.setText("Fecha de Recepción: " + sdf.format(data.getFechaRecepcionRecurso()));

    String disponibilidad = data.getDisponibilidadRecurso();
    lblDisponibilidad.setText(disponibilidad);
    
    // Cambiar el color del texto de disponibilidad si es necesario
    if ("En uso".equalsIgnoreCase(disponibilidad) ) {
        lblDisponibilidad.setForeground(Color.RED);
    } else if( "Disponible".equalsIgnoreCase(disponibilidad)) {
        lblDisponibilidad.setForeground(Color.GREEN); // Color por defecto, ajusta según tus necesidades
    }
}


private ImageIcon redimensionarImagen(String rutaImagen, int ancho, int alto) {
    ImageIcon imagenOriginal = new ImageIcon(rutaImagen);
    Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
    return new ImageIcon(imagenEscalada);
}


    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(255,173,122));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        if (selected) {
            g2.setColor(new Color(94, 156, 255));
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }
        g2.dispose();
        super.paint(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgRecurso = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDisponibilidad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 173, 122));

        lblFecha.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha de recepción");

        lblNombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Text");

        lblDisponibilidad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        lblDisponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        lblDisponibilidad.setText("Disponibilidad");

        lblDescripcion.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripción del recurso");

        lblEstado.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado del recurso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDisponibilidad)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNombre)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha)
                .addGap(18, 18, 18)
                .addComponent(lblDisponibilidad)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgRecurso;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblDisponibilidad;
    public javax.swing.JLabel lblEstado;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
